import { List } from 'lucide-react'

/**
 * Auto-generated Table of Contents for blog posts.
 *
 * Parses `## ` H2 headings out of the MDX at render time, generates a
 * kebab-case slug for each, and emits a jump-anchor list at the top of
 * the article. Two payoffs:
 *
 *   1. UX  — readers scan the outline before committing to the read.
 *   2. SEO — Google frequently promotes TOC anchor links as "Jump to"
 *            sitelinks under the main SERP result, and the anchor IDs
 *            themselves become URL-fragment hits (`#gstr-3b-late-fee`)
 *            that appear in search suggestions.
 *
 * Renders nothing when there are fewer than 3 H2s — a short article
 * doesn't need a TOC and would look silly with one.
 *
 * Server-only, no state — the anchor targets are generated by react-
 * markdown's default slug behaviour, which we mirror here so link IDs
 * match the actual DOM.
 */

const MIN_H2_FOR_TOC = 3

export function TableOfContents({ mdx }: { mdx: string }) {
  const entries = extractH2s(mdx)
  if (entries.length < MIN_H2_FOR_TOC) return null

  return (
    <nav
      aria-label="Table of contents"
      className="mb-10 rounded-2xl border border-border bg-bg-elev/60 p-6"
    >
      <div className="mb-3 flex items-center gap-2 font-mono text-[11px] uppercase tracking-wider text-fg-subtle">
        <List className="h-3.5 w-3.5" />
        In this article
      </div>
      <ol className="space-y-2 text-sm">
        {entries.map((e, i) => (
          <li key={e.slug} className="flex items-start gap-3">
            <span className="mt-0.5 w-6 shrink-0 font-mono text-[11px] text-fg-subtle tabular-nums">
              {String(i + 1).padStart(2, '0')}
            </span>
            <a
              href={`#${e.slug}`}
              className="text-fg-muted underline-offset-4 hover:text-accent hover:underline"
            >
              {e.text}
            </a>
          </li>
        ))}
      </ol>
    </nav>
  )
}

/**
 * Extract H2 headings — anything on its own line starting with `## `
 * that isn't inside a fenced code block.
 */
export function extractH2s(mdx: string): Array<{ text: string; slug: string }> {
  if (!mdx) return []
  // Strip fenced code blocks so a `## Foo` inside a `js code sample`
  // doesn't get promoted to a real heading.
  const stripped = mdx.replace(/```[\s\S]*?```/g, '')
  const lines = stripped.split(/\r?\n/)
  const entries: Array<{ text: string; slug: string }> = []
  const seen = new Set<string>()

  for (const line of lines) {
    const m = /^\s*##\s+(?!#)(.+?)\s*#*\s*$/.exec(line)
    if (!m || !m[1]) continue
    const text = stripInlineMarkdown(m[1]).trim()
    if (!text) continue
    let slug = slugify(text)
    // Handle duplicate headings — react-markdown appends -1, -2, …
    // We mirror that so anchor links still match the DOM.
    let n = 1
    let candidate = slug
    while (seen.has(candidate)) {
      candidate = `${slug}-${n}`
      n++
    }
    slug = candidate
    seen.add(slug)
    entries.push({ text, slug })
  }
  return entries
}

/** Strip inline markdown so "**bold** _italic_ `code`" reads clean. */
function stripInlineMarkdown(s: string): string {
  return s
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/__([^_]+)__/g, '$1')
    .replace(/_([^_]+)_/g, '$1')
    .replace(/!?\[([^\]]+)\]\([^)]+\)/g, '$1')
}

/** kebab-case slug matching react-markdown's default rehype-slug behaviour. */
function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '') // strip diacritics
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}
