/**
 * Renders the markdown triage report.
 * Pure function — takes scored blocks + aggregates, returns a string.
 */

import { explainBlock, briefFix, suggestRewrite } from './rewrite.mjs'

const FLAG_THRESHOLD = 15

/**
 * @param {{
 *   today: string,
 *   lessonsAudited: number,
 *   allBlocks: any[],
 *   flagged: any[],
 *   buckets: Record<string, number>,
 *   heuristicHits: Record<string, number>,
 *   typeTally: Record<string, number>,
 * }} args
 */
export function renderMarkdown(args) {
  const { today, lessonsAudited, allBlocks, flagged, buckets, heuristicHits, typeTally } = args
  /** @param {string} s */
  const esc = (s) => (s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')

  const lines = []
  lines.push(`# Lesson Flowchart Audit — ${today}`)
  lines.push('')
  lines.push('> Static triage of every Mermaid source attached to a CurriculumLesson.')
  lines.push('> Generated by `scripts/audit-flowcharts.mjs`. Re-runnable. No content is mutated.')
  lines.push('')
  lines.push(`- **Lessons audited:** ${lessonsAudited}`)
  lines.push(`- **Mermaid blocks found:** ${allBlocks.length}`)
  lines.push(`- **Blocks flagged (score ≥ ${FLAG_THRESHOLD}):** ${flagged.length}`)
  lines.push('')

  if (allBlocks.length === 0) {
    lines.push('## Nothing to audit')
    lines.push('')
    lines.push('No mermaid sources were found in any CurriculumLesson. This means either:')
    lines.push('')
    lines.push('1. The curriculum has not been seeded yet (run the curriculum generation pipeline), or')
    lines.push(
      '2. Lessons exist but neither `flowchartMermaid`/`mindmapMermaid` columns nor ` ```mermaid` ` fenced blocks in `contentEnMdx`/`contentArMdx` are populated.',
    )
    lines.push('')
    lines.push('Re-run after seeding.')
    return lines.join('\n')
  }

  renderSystemic(lines, allBlocks, heuristicHits)
  renderHistogram(lines, buckets)
  renderTypeTally(lines, typeTally)
  renderHeuristicHits(lines, heuristicHits)
  renderTop50(lines, flagged, esc)
  renderTop10(lines, flagged)
  renderMethod(lines)

  return lines.join('\n')
}

function renderSystemic(lines, allBlocks, heuristicHits) {
  lines.push('## Systemic issues (act on these first)')
  lines.push('')
  const total = allBlocks.length
  const pct = (n) => `${n} (${Math.round((n / total) * 100)}%)`
  const sys = []
  if (heuristicHits.noOrientation / Math.max(1, total) > 0.3) {
    sys.push(
      `- **No explicit \`flowchart LR/TD\` orientation** in ${pct(heuristicHits.noOrientation)} of blocks. ` +
        `Mermaid's default top-down rarely matches the intent and produces tall, narrow charts that overflow the lesson viewport. ` +
        'Recommend a sed-style cleanup: prepend `flowchart LR` to any block whose first non-comment line is a bare `graph` or `flowchart`.',
    )
  }
  if (heuristicHits.unquotedParensInSquares > 0) {
    sys.push(
      `- **Unquoted parentheses inside \`[...]\` labels** in ${pct(heuristicHits.unquotedParensInSquares)} of blocks. ` +
        `Mermaid parses inner \`(\`/\`)\` as a different node shape, turning labels into garbage. ` +
        'Fix: wrap any `[Label (qualifier)]` body in double-quotes — `["Label (qualifier)"]`.',
    )
  }
  if (heuristicHits.unusualType > 0) {
    sys.push(
      `- **Non-flowchart diagram types** (\`sequenceDiagram\`/\`gantt\`/\`classDiagram\`) used in ${pct(heuristicHits.unusualType)} of blocks. ` +
        `These don't match the curriculum aesthetic and render at different font scales than the flowchart fix that just shipped. ` +
        'Recommend converting to `flowchart LR` where the intent is procedural.',
    )
  }
  if (heuristicHits.tooManyNodes / Math.max(1, total) > 0.2) {
    sys.push(
      `- **Oversized flowcharts** (>12 nodes) in ${pct(heuristicHits.tooManyNodes)} of blocks. ` +
        `These are the "messy and cluttered" complaint from the strategy review. ` +
        'Recommend splitting into 2–3 sequential smaller charts per lesson.',
    )
  }
  if (sys.length === 0) {
    lines.push('_None — the corpus is generally clean. Focus on the individual top offenders below._')
  } else {
    for (const s of sys) lines.push(s)
  }
  lines.push('')
}

function renderHistogram(lines, buckets) {
  lines.push('## Score distribution')
  lines.push('')
  lines.push('| bucket | count |')
  lines.push('|---|---|')
  for (const [k, v] of Object.entries(buckets)) lines.push(`| ${k} | ${v} |`)
  lines.push('')
}

function renderTypeTally(lines, typeTally) {
  lines.push('## Chart types in use')
  lines.push('')
  lines.push('| type | count |')
  lines.push('|---|---|')
  const sorted = Object.entries(typeTally).sort((a, b) => b[1] - a[1])
  for (const [k, v] of sorted) lines.push(`| \`${k}\` | ${v} |`)
  lines.push('')
}

function renderHeuristicHits(lines, h) {
  lines.push('## Heuristic hits')
  lines.push('')
  lines.push('| heuristic | blocks hit |')
  lines.push('|---|---|')
  lines.push(`| No explicit orientation | ${h.noOrientation} |`)
  lines.push(`| Unquoted \`(\`/\`)\` in \`[...]\` | ${h.unquotedParensInSquares} |`)
  lines.push(`| Unquoted special chars (\`&%/:—\`) | ${h.unquotedSpecialChars} |`)
  lines.push(`| Too many nodes (>12) | ${h.tooManyNodes} |`)
  lines.push(`| Too many lines (>20) | ${h.tooManyLines} |`)
  lines.push(`| Too many subgraphs (>3) | ${h.tooManySubgraphs} |`)
  lines.push(`| Unusual chart type | ${h.unusualType} |`)
  lines.push('')
}

function renderTop50(lines, flagged, esc) {
  lines.push('## Top 50 worst offenders')
  lines.push('')
  lines.push('Sorted by total score, descending.')
  lines.push('')
  lines.push('| score | lesson slug | titleEn | origin | flags |')
  lines.push('|---|---|---|---|---|')
  const top50 = flagged.slice(0, 50)
  if (top50.length === 0) {
    lines.push(`| _no blocks scored ≥ ${FLAG_THRESHOLD}_ |  |  |  |  |`)
  } else {
    for (const b of top50) {
      lines.push(
        `| ${b.score.total} | \`${esc(b.slug)}\` | ${esc(b.titleEn)} | \`${esc(b.origin)}\` | ${b.score.flags.map((f) => '`' + f + '`').join(' ')} |`,
      )
    }
  }
  lines.push('')
}

function renderTop10(lines, flagged) {
  lines.push('## Top 10 — detailed breakdown')
  lines.push('')
  if (flagged.length === 0) {
    lines.push('_No blocks crossed the threshold. Skipping detail section._')
    lines.push('')
    return
  }
  const top10 = flagged.slice(0, 10)
  for (let i = 0; i < top10.length; i++) {
    const b = top10[i]
    lines.push(`### ${i + 1}. \`${b.slug}\` — ${b.titleEn}`)
    lines.push('')
    lines.push(
      `- **Track:** ${b.track ?? '—'}  ·  **Module:** ${b.module ?? '—'}  ·  **Origin:** \`${b.origin}\``,
    )
    lines.push(`- **Score:** ${b.score.total}`)
    lines.push(`- **Flags:** ${b.score.flags.map((f) => '`' + f + '`').join(' ') || '_none_'}`)
    lines.push('')
    lines.push('**Score breakdown:**')
    lines.push('')
    lines.push('| heuristic | points |')
    lines.push('|---|---|')
    for (const [k, v] of Object.entries(b.score.breakdown)) {
      if (v > 0) lines.push(`| ${k} | ${v} |`)
    }
    lines.push('')
    lines.push('**Source:**')
    lines.push('')
    lines.push('```mermaid')
    lines.push(b.source)
    lines.push('```')
    lines.push('')
    lines.push("**Why it's flagged:**")
    lines.push('')
    lines.push(explainBlock(b))
    lines.push('')
    if (i < 5) {
      lines.push('**Suggested rewrite:**')
      lines.push('')
      for (const part of suggestRewrite(b)) {
        lines.push('```mermaid')
        lines.push(part)
        lines.push('```')
        lines.push('')
      }
    } else {
      lines.push(`**Suggested fix:** ${briefFix(b)}`)
      lines.push('')
    }
    lines.push('---')
    lines.push('')
  }
}

function renderMethod(lines) {
  lines.push('## Method')
  lines.push('')
  lines.push('Score = sum of:')
  lines.push('')
  lines.push('- `(nodeCount − 12) × 2` if nodeCount > 12 (clutter starts ~12 nodes)')
  lines.push('- `(lineCount − 20) × 1.5` if lineCount > 20')
  lines.push('- `unquoted ( ) in [ ] labels × 5` (very likely render breakage)')
  lines.push('- `unquoted &, %, /, :, em-dashes × 2`')
  lines.push('- `(subgraphCount − 3) × 4` if subgraphCount > 3')
  lines.push('- `+3` if no explicit `flowchart LR/TD/...` orientation')
  lines.push('- `+5` if the diagram is `sequenceDiagram`/`gantt`/`classDiagram`')
  lines.push('')
  lines.push(
    'Blocks scoring **≥ 15** are flagged. The renderer (`apps/web/src/components/lesson/mermaid-block.tsx`) sanitises some of these at render time, but content-level fixes are still required to communicate the curriculum cleanly.',
  )
  lines.push('')
}
